### ISSUE TITLE
Allow failed instances to be stopped

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2468] opened 2024-09-24 17:29 UTC
Also rebooted maybe?

https://github.com/oxidecomputer/omicron/pull/6652

**Comment by hawkw** [comment] 2024-09-24 18:05
> Also rebooted maybe?

I believe `Failed` instances can be _restarted_ by `PUT /v1/instances/{id}/start`, but not _rebooted_ by `PUT /v1/instances/{id}/reboot`. The "reboot" API doesn't start a stopped/failed instance on a new VMM, but instead instructs the existing VMM to reboot the guest (as though the guest was power-cycled, essentially). That doesn't work when there is no VMM --- the instance will have to be started first.

**Comment by charliepark** [comment] 2024-09-28 00:19
#2481 looks to be a duplicate of this, though I don't know that I have enough context on the rebooting conversation above to know if it's an exhaustive duplicate or only a partial duplicate.

**Comment by hawkw** [comment] 2024-09-28 00:37
@charliepark I think #2481 is definitely a duplicate of this. Re: rebooting, we should not allow rebooting a `Failed` instance, since that will just result in Nexus returning an error anyway. I'd probably keep this issue over #2481 since it has that additional context.

**Comment by hawkw** [comment] 2024-09-28 00:40
Oh, if #2482 closes #2481, it should definitely also close this --- the rebooting thing is just kinda a red herring.

**Comment by charliepark** [comment] 2024-09-28 00:52
Solid; will update #2482 and close #2481.

**Comment by askfongjojo** [comment] 2024-09-28 03:06
Sorry about the dup. I should have checked before filing it. 😓

**Comment by charliepark** [comment] 2024-09-28 03:09
No worries! It was actually seeing your issue that prompted my working on the fix, so it all worked out. 🙂

**Closed** 2024-09-30 16:24 UTC
