### ISSUE TITLE
Warn user before closing Add Firewall Rule form when clicking out of the form

### ISSUE THREAD

**Issue by charliepark** [oxidecomputer/console#2310] opened 2024-07-03 14:50 UTC
This might be a duplicate issue, but I wanted to capture it anyway.

We should warn the user when they click out of the Add Firewall Rule form, rather than just blowing away the side modal. It's a complicated enough form that will require enough focused time, losing that data would be really frustrating.

**Comment by david-crespo** [comment] 2024-07-03 15:12
Dupe of 

* #2186

We can solve this for every form at once.

**Closed by david-crespo** 2024-07-03 15:12 UTC
