### ISSUE TITLE
[nics] Error returned when optional field not set

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/console#1851] opened 2023-12-11 22:21 UTC
When adding a custom network interface I got an error when I didn't set the optional IP address field

![Screenshot from 2023-12-12 11-16-37](https://github.com/oxidecomputer/console/assets/7670244/c094a5ec-65ab-4f32-93ec-2957243e04ba)
![Screenshot from 2023-12-12 11-16-59](https://github.com/oxidecomputer/console/assets/7670244/fa079a24-16c8-43d8-864d-30610d3294b1)

**Comment by david-crespo** [comment] 2023-12-11 22:30
Dupe of #1438, which was half-fixed by #1811 — it will no longer error as long as you don't type something in the field and delete it, which probably covers 99% of use. That fix is out on dogfood but not on colo.

**Closed by david-crespo** 2023-12-11 22:30 UTC
Labels: bug

**Comment by charliepark** [comment] 2023-12-12 23:27
Should be fully fixed by #1854
