### ISSUE TITLE
Disallow disk snapshots for disks attached to stopped instances

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1947] opened 2024-02-08 20:13 UTC
Currently the web console allows for attempting to snapshot a disk that is attached to a stopped instance. This is currently not supported in nexus and either the instance needs to be running, or the disk needs to be detached for us to be able to snapshot it. We should not present the option to snapshot under these conditions.

**Comment by david-crespo** [comment] 2024-02-08 20:22
Found what looks like the relevant check. It has been there since snapshots were introduced.

https://github.com/oxidecomputer/omicron/blob/a5430a6465f457175ca1cf0c0053ffc47f25bf62/sled-agent/src/instance.rs#L1183-L1203

**Comment by david-crespo** [comment] 2024-02-20 20:58
Tested snapshotting a disk attached to a stopped instance on dogfood with #1948 deployed.

![Screenshot 2024-02-20 at 2 56 54 PM](https://github.com/oxidecomputer/console/assets/3612203/6308c9e2-d78f-4108-a43a-d48b60ace67e)

It's not great, but it would be better if the API error message was better.

```json
{
  "request_id": "f14e26d3-f122-4f12-b284-daf99c2386c3",
  "error_code": "ServiceNotAvailable",
  "message": "Service Unavailable"
}
```

**Comment by david-crespo** [comment] 2024-02-20 21:08
I was wrong, the error comes from Nexus, right in the saga.

https://github.com/oxidecomputer/omicron/blob/915276d47096a9ce076453eb75aaa9de29477e80/nexus/src/app/sagas/snapshot_create.rs#L841-L851

**Comment by augustuswm** [comment] 2024-02-21 15:29
That is unfortunate. Maybe `snapshot_create` needs to check that invariant before issuing the saga given that we know it will fail. As it should really be using a 4xx status code like the other invariant failures as opposed to a 503, since no amount of calling the endpoint will succeed.

**Comment by david-crespo** [comment] 2024-02-21 15:55
I think it might be a bug, as there is such a check before starting the saga. The logic might not be quite right.

https://github.com/oxidecomputer/omicron/issues/5108

**Comment by askfongjojo** [comment] 2024-03-12 19:16
We probably want to hold this ticket for a bit as https://github.com/oxidecomputer/omicron/issues/3289 is being fixed by https://github.com/oxidecomputer/omicron/issues/5221. Hopefully we no longer have to deal with the 503 error for much longer.

**Comment by askfongjojo** [comment] 2024-04-15 16:03
I just confirmed on rack2 that we can now snapshot disks attached to stopped instance. The change requested here is no longer necessary.

**Closed by askfongjojo** 2024-04-15 16:03 UTC
Labels: bug
