### ISSUE TITLE
Add floating ip dropdown to instance creation advanced networking

### ISSUE THREAD

**Issue by taspelund** [oxidecomputer/console#2212] opened 2024-05-01 00:25 UTC
It would be nice to have the option to create/attach a floating IP during instance creation.
I envision this as a dropdown accessible from Advanced -> Networking -> Floating IPs

**Comment by david-crespo** [comment] 2024-05-01 00:49
Dupe of #1099, we have designs very similar to that.

**Closed by david-crespo** 2024-05-01 00:49 UTC
Labels: idea
