### ISSUE TITLE
SSH keys automatically added to new instances

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/console#1847] opened 2023-12-11 21:53 UTC
When spinning up a new instance, all the SSH keys I had saved were automatically added. Sometimes you don't want all of them added to a specific instance for a myriad of reasons, but you don't want to remove them from your saved SSH keys. I realise it's a feature of the product to have this functionality, but I spent some time trying to figure out how to remove SSH keys from the list of keys to be added to my instance.

Perhaps a note explaining that all keys are automatically added by design will save people time trying to figure out how to modify this list.

![Screenshot from 2023-12-12 10-51-16](https://github.com/oxidecomputer/console/assets/7670244/c2a37e15-ff85-421d-a28d-55e39a9389c1)

**Comment by benjaminleonard** [comment] 2023-12-11 22:00
Agreed! Already covered in #1818.

**Comment by karencfv** [comment] 2023-12-11 23:48
Ah sweet! In the mean time, just adding some text saying that the list of ssh-keys can't be modified per instance might be good?

**Comment by david-crespo** [comment] 2023-12-18 18:43
Closing as duplicate of #1818. Since the above suggestion about a message didn't make it into the current release, we don't need it because we're going to fix it for real in the next release.

**Closed by david-crespo** 2023-12-18 18:43 UTC
Labels: idea
